import { Todo } from "../types/todo"
import { createTodo, fetchTodos, deleteTodo, updateTodo } from '../utils/api';
import { useState } from "react";
import EditWindow from "./EditWindow";

interface Editing {
    win: boolean,
    id: string
}

interface Props {
    todo: Todo,
    setTodoList: React.Dispatch<React.SetStateAction<Todo[]>>;
    setEditingTodo: React.Dispatch<React.SetStateAction<Editing>>;
}

// convert date mainly for the linux autogenerated date
const convertDate = (dateString: string) => {
    // Ensure the date string is in the correct format
    const regex = /^\d{4}-\d{2}-\d{2}$/;
    if (!regex.test(dateString)) {
        throw new Error("Date string is not in the format yyyy-mm-dd");
    }

    // Split the date string into components
    const [year, month, day] = dateString.split('-');
    const shortYear = year.slice(-2);

    return `${day}/${month}/${shortYear}`;
}

// what to do:
// [] - before passing the todolist, sort the list by priority, then not done items and lastly done items
// [x] - format the linux date to get dd/mm/yy 

const TodoItem: React.FC<Props> = ({ todo, setTodoList, setEditingTodo }) => {
    
    const handleUpdate = async(id: string, fields: Partial<Todo>) => {
        try {
            const updatedTodo = await updateTodo(id, fields);
            setTodoList((prevTodos) => prevTodos.map((todo) => (todo.id === id ? updatedTodo : todo)));
        } catch(error) {
            console.error(`Failed to update todo id: ${id}: `, error);
        };
    }

    const handleDelete = async (id: string) => {
        try {
            await deleteTodo(id);
            setTodoList(prev => prev.filter(todo => todo.id !== id));
        } catch(error) {
            console.error(`Failed to update todo id: ${id}: `, error);
        };
    }

    const handleEdit = (id: string) => {
        setEditingTodo({
            win: true,
            id: id
        })
    }

    return (
        <div 
            style={{
                backgroundColor: !todo.priority ? `${todo.complete ? 'rgb(229 231 235)' : 'rgb(243 244 246)'}` : 'rgb(250 204 21)',
                color: todo.complete && 'rgb(156 163 175)'
            }} 
            className="flex flex-col w-full p-2 rounded-md shadow-xl"
        >
            <div className="flex flex-row justify-between text-sm">
                <p>
                    Due: {convertDate(todo.duedate)}
                </p>
                <p className="text-gray-400">
                    Created: {convertDate(todo.createdate)}
                </p>
            </div>
            <div className="flex flex-row justify-between p-2">
                <div className="m-auto">
                    <input className="size-[20px]" 
                        type="checkbox" 
                        checked={todo.complete}
                        onChange={() => handleUpdate(todo.id, {complete: !todo.complete})}
                    />

                </div>
                <div className="flex flex-grow items-center justify-center p-2">
                    <h1 className="text-lg font-bold">{todo.text}</h1>
                </div>
                <div className="flex flex-row items-center gap-2">
                    <div onClick={() => handleEdit(todo.id)} className="cursor-pointer">
                        edit
                    </div>
                    <div className="cursor-pointer" onClick={() => handleDelete(todo.id)}>
                        del
                    </div>
                </div>

            </div>

            <div className="w-full flex flex-col items-start text-sm text-gray-500">
                {todo.tags.map(a => `#${a}`).join(', ')}
            </div>
        </div>
    )
}

export default TodoItem