import { useRouter } from "next/navigation";
import { SelectSwitch, Todo } from "../types/todo"
import { deleteTodo, fetchTodos, updateTodo } from '../utils/api';
import { todayDate } from "../utils/date-functions";
import { useState } from "react";

interface Editing {
    win: boolean,
    id: string
}

interface Props {
    selectSwitch: SelectSwitch;
    todo: Todo,
    page: string;
    listLength: number;
    setTodoList: React.Dispatch<React.SetStateAction<Todo[]>>;
    setEditingTodo: React.Dispatch<React.SetStateAction<Editing>>;
}

// convert date mainly for the linux autogenerated date
const convertDate = (dateString: string) => {
    // Ensure the date string is in the correct format
    const regex = /^\d{4}-\d{2}-\d{2}$/;


    // Split the date string into components
    const [year, month, day] = dateString.split('-');
    const shortYear = year.slice(-2);

    return `${day}/${month}/${shortYear}`;
}

const TodoItem: React.FC<Props> = ({ selectSwitch, todo, page, listLength, setTodoList, setEditingTodo }) => {
    const router = useRouter();
    
    const fetchData = () => {
        fetchTodos()
        .then(data => {
            setTodoList(data.filter(a => a.list === page))
        })
        .catch(error => console.error('Failed to fetch todos', error));
    }

    const handleUpdate = async(id: string, fields: Partial<Todo>) => {
        try {
            const updatedTodo = await updateTodo(id, fields);
            setTodoList((prevTodos) => prevTodos.map((todo) => (todo.id === id ? updatedTodo : todo)));

            fetchData();
                
        } catch(error) {
            console.error(`Failed to update todo id: ${id}: `, error);
        };
    }

    const handleDelete = async (id: string) => {
        var result = confirm("Are you sure you want to delete this Item?");
        if (result) {
            try {
                await deleteTodo(id);
                if (listLength === 1) {
                    router.push('main')
                }
                fetchData();
            } catch(error) {
                console.error(`Failed to update todo id: ${id}: `, error);
            };
        }
    };

    const handleEdit = (id: string) => {
        setEditingTodo({
            win: true,
            id: id
        });
    };

    const selectAllCondition = selectSwitch.all
    const selectCondition = selectSwitch.multi && selectSwitch.multiSelectItems.includes(todo.id) || selectAllCondition

    return (
        <div 
            style={{
                // backgroundColor: !todo.priority ? `${todo.complete ? 'rgb(229 231 235)' : 'rgb(243 244 246)'}` : `${todo.complete ? 'rgb(254 240 138)' : 'rgb(250 204 21)'}`,
                color: todo.complete ? 'rgb(156 163 175)' : '',
                filter: todo.complete ? '' : 'drop-shadow(0 10px 8px rgb(0 0 0 / 0.04)) drop-shadow(0 4px 3px rgb(0 0 0 / 0.1)) drop-shadow(0 1.2px 1.2px rgb(0 0 0 / 0.8))',
                outline: selectCondition ? '6px solid rgb(107 114 128)' : ''
            }} 
            className={`flex flex-col sm:justify-between w-full p-2 rounded-md ${!todo.priority ? `${todo.complete ? 'bg-gray-200 dark:bg-gray-600' : 'dark:text-gray-400 bg-gray-100 dark:bg-gray-800'} ` : 'bg-yellow-400 dark:bg-yellow-500'}`}
        >
            <div className="flex flex-row justify-between text-sm">
                <p>
                    Due: {convertDate(todo.duedate)}
                </p>
                <p className="text-gray-400">
                    Created: {convertDate(todo.createdate)}
                </p>
            </div>

            <div className="flex flex-row justify-between p-2">

                {/* checkbox */}
                <div className="m-auto">
                    <input className="size-[30px] dark:bg-gray-600 cursor-pointer accent-gray-600" 
                        type="checkbox" 
                        checked={todo.complete}
                        onChange={() => handleUpdate(todo.id, {complete: !todo.complete, checkdate: todayDate()})}
                    />
                </div>

                {/* todo text */}
                <div style={{textDecorationLine: todo.complete ? 'line-through' : 'none'}} className="line-through flex flex-grow items-center justify-center px-4 p-2 cursor-pointer">
                    <h1 onClick={() => handleEdit(todo.id)} style={{}} className="text-lg font-bold">{todo.text}</h1>
                </div>

                {/* delete and edit buttons */}
                <div className="flex flex-row items-center gap-2">
                    <div onClick={() => handleEdit(todo.id)} className="cursor-pointer">
                        edit
                    </div>
                    <div className="cursor-pointer" onClick={() => handleDelete(todo.id)}>
                        del
                    </div>
                </div>

            </div>

            <div className="w-full flex flex-col items-start text-sm text-gray-500">
                {todo.tags.map(a => `#${a}`).join(', ')}
            </div>
        </div>
    )
}

export default TodoItem